# Generated by Django 5.1.6 on 2025-05-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_stream_user_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='post_id',
        ),
    ]
