# Generated by Django 5.1.6 on 2025-05-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_id_post_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='id',
        ),
    ]
